"use strict";(self.webpackChunk=self.webpackChunk||[]).push([[7724],{8205:(e,r,n)=>{n.r(r),n.d(r,{assets:()=>l,contentTitle:()=>a,default:()=>h,frontMatter:()=>s,metadata:()=>i,toc:()=>d});var o=n(5893),t=n(1151);const s={title:"errorElement",new:!0,sidebar_position:void 0},a="errorElement",i={id:"route/error-element",title:"errorElement",description:"When exceptions are thrown in loaders, actions, or component rendering, instead of the normal render path for your Routes (`), the error path will be rendered () and the error made available with useRouteError`.",source:"@site/react-router/docs/route/error-element.md",sourceDirName:"route",slug:"/route/error-element",permalink:"/react-router-v6-searchable-docs/route/error-element",draft:!1,unlisted:!1,tags:[],version:"current",lastUpdatedAt:1702600842,formattedLastUpdatedAt:"Dec 15, 2023",frontMatter:{title:"errorElement",new:!0},sidebar:"tutorialSidebar",previous:{title:"action",permalink:"/react-router-v6-searchable-docs/route/action"},next:{title:"hydrateFallbackElement",permalink:"/react-router-v6-searchable-docs/route/hydrate-fallback-element"}},l={},d=[{value:"Bubbling",id:"bubbling",level:2},{value:"Default Error Element",id:"default-error-element",level:3},{value:"Throwing Manually",id:"throwing-manually",level:2},{value:"Throwing Responses",id:"throwing-responses",level:2},{value:"Abstractions",id:"abstractions",level:2}];function c(e){const r={a:"a",code:"code",em:"em",h1:"h1",h2:"h2",h3:"h3",p:"p",pre:"pre",...(0,t.a)(),...e.components};return(0,o.jsxs)(o.Fragment,{children:[(0,o.jsx)(r.h1,{id:"errorelement",children:(0,o.jsx)(r.code,{children:"errorElement"})}),"\n",(0,o.jsxs)(r.p,{children:["When exceptions are thrown in ",(0,o.jsx)(r.a,{href:"./loader",children:"loaders"}),", ",(0,o.jsx)(r.a,{href:"./action",children:"actions"}),", or component rendering, instead of the normal render path for your Routes (",(0,o.jsx)(r.code,{children:"<Route element>"}),"), the error path will be rendered (",(0,o.jsx)(r.code,{children:"<Route errorElement>"}),") and the error made available with ",(0,o.jsx)(r.a,{href:"../hooks/use-route-error",children:(0,o.jsx)(r.code,{children:"useRouteError"})}),"."]}),"\n",(0,o.jsxs)("docs-info",{children:["If you do not wish to specify a React element (i.e., ",(0,o.jsx)(r.code,{children:"errorElement={<MyErrorBoundary />}"}),") you may specify an ",(0,o.jsx)(r.code,{children:"ErrorBoundary"})," component instead (i.e., ",(0,o.jsx)(r.code,{children:"ErrorBoundary={MyErrorBoundary}"}),") and React Router will call ",(0,o.jsx)(r.code,{children:"createElement"})," for you internally."]}),"\n",(0,o.jsxs)("docs-warning",{children:["This feature only works if using a data router, see ",(0,o.jsx)(r.a,{href:"../routers/picking-a-router",children:"Picking a Router"})]}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:'<Route\n  path="/invoices/:id"\n  // if an exception is thrown here\n  loader={loadInvoice}\n  // here\n  action={updateInvoice}\n  // or here\n  element={<Invoice />}\n  // this will render instead of `element`\n  errorElement={<ErrorBoundary />}\n/>;\n\nfunction Invoice() {\n  return <div>Happy {path}</div>;\n}\n\nfunction ErrorBoundary() {\n  let error = useRouteError();\n  console.error(error);\n  // Uncaught ReferenceError: path is not defined\n  return <div>Dang!</div>;\n}\n'})}),"\n",(0,o.jsx)(r.h2,{id:"bubbling",children:"Bubbling"}),"\n",(0,o.jsxs)(r.p,{children:["When a route does not have an ",(0,o.jsx)(r.code,{children:"errorElement"}),", errors will bubble up through parent routes. This lets you get as granular or general as you like."]}),"\n",(0,o.jsxs)(r.p,{children:["Put an ",(0,o.jsx)(r.code,{children:"errorElement"})," at the top of your route tree and handle nearly every error in your app in one place. Or, put them on all of your routes and allow the parts of the app that don't have errors to continue to render normally. This gives the user more options to recover from errors instead of a hard refresh and \ud83e\udd1e."]}),"\n",(0,o.jsx)(r.h3,{id:"default-error-element",children:"Default Error Element"}),"\n",(0,o.jsxs)("docs-warning",{children:["We recommend ",(0,o.jsx)(r.em,{children:"always"})," providing at least a root-level ",(0,o.jsx)(r.code,{children:"errorElement"})," before shipping your application to production, because the UI of the default ",(0,o.jsx)(r.code,{children:"errorElement"})," is ugly and not intended for end-user consumption."]}),"\n",(0,o.jsxs)(r.p,{children:["If you do not provide an ",(0,o.jsx)(r.code,{children:"errorElement"})," in your route tree to handle a given error, errors will bubble up and be handled by a default ",(0,o.jsx)(r.code,{children:"errorElement"})," which will print the error message and stack trace. Some folks have questioned why the stack trace shows up in production builds. Normally, you don't want to expose stack traces on your production sites for security reasons. However, this is more applicable to server-side errors (and Remix does indeed strip stack traces from server-side loader/action responses). In the case of client-side ",(0,o.jsx)(r.code,{children:"react-router-dom"})," applications the code is already available in the browser anyway so any hiding is just security through obscurity. Furthermore, we would still want to expose the error in the console, so removing it from the UI display is still not hiding any information about the stack trace. Not showing it in the UI ",(0,o.jsx)(r.em,{children:"and"})," not logging it to the console would mean that application developers have no information ",(0,o.jsx)(r.em,{children:"at all"})," about production bugs, which poses its own set of issues. So, again we recommend you always add a root level ",(0,o.jsx)(r.code,{children:"errorElement"})," before deploying your site to production!"]}),"\n",(0,o.jsx)(r.h2,{id:"throwing-manually",children:"Throwing Manually"}),"\n",(0,o.jsxs)(r.p,{children:["While ",(0,o.jsx)(r.code,{children:"errorElement"})," handles unexpected errors, it can also be used to handle exceptions you expect."]}),"\n",(0,o.jsxs)(r.p,{children:["Particularly in loaders and actions, where you work with external data not in your control, you can't always plan on the data existing, the service being available, or the user having access to it. In these cases you can ",(0,o.jsx)(r.code,{children:"throw"})," your own exceptions."]}),"\n",(0,o.jsxs)(r.p,{children:['Here\'s a "not found" case in a ',(0,o.jsx)(r.a,{href:"./loader",children:"loader"}),":"]}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",metastring:"[4,7-9]",children:'<Route\n  path="/properties/:id"\n  element={<PropertyForSale />}\n  errorElement={<PropertyError />}\n  loader={async ({ params }) => {\n    const res = await fetch(`/api/properties/${params.id}`);\n    if (res.status === 404) {\n      throw new Response("Not Found", { status: 404 });\n    }\n    const home = await res.json();\n    const descriptionHtml = parseMarkdown(\n      data.descriptionMarkdown\n    );\n    return { home, descriptionHtml };\n  }}\n/>\n'})}),"\n",(0,o.jsx)(r.p,{children:"As soon as you know you can't render the route with the data you're loading, you can throw to break the call stack. You don't have to worry about the rest of the work in the loader (like parsing the user's markdown bio) when it doesn't exist. Just throw and get out of there."}),"\n",(0,o.jsxs)(r.p,{children:["This also means you don't have to worry about a bunch of error branching code in your route component. It won't even try to render if you throw in the loader or action, since your ",(0,o.jsx)(r.code,{children:"errorElement"})," will render instead."]}),"\n",(0,o.jsx)(r.p,{children:"You can throw anything from a loader or action just like you can return anything: responses (like the previous example), errors, or plain objects."}),"\n",(0,o.jsx)(r.h2,{id:"throwing-responses",children:"Throwing Responses"}),"\n",(0,o.jsxs)(r.p,{children:["While you can throw anything and it will be provided back to you through ",(0,o.jsx)(r.a,{href:"../hooks/use-route-error",children:(0,o.jsx)(r.code,{children:"useRouteError"})}),", if you throw a ",(0,o.jsx)(r.a,{href:"https://developer.mozilla.org/en-US/docs/Web/API/Response",children:"Response"}),", React Router will automatically parse the response data before returning it to your components."]}),"\n",(0,o.jsxs)(r.p,{children:["Additionally, ",(0,o.jsx)(r.a,{href:"../utils/is-route-error-response",children:(0,o.jsx)(r.code,{children:"isRouteErrorResponse"})})," lets you check for this specific type in your boundaries. Coupled with ",(0,o.jsx)(r.a,{href:"../fetch/json",children:(0,o.jsx)(r.code,{children:"json"})}),", you can easily throw responses with some data and render different cases in your boundary:"]}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:'import { json } from "react-router-dom";\n\nfunction loader() {\n  const stillWorksHere = await userStillWorksHere();\n  if (!stillWorksHere) {\n    throw json(\n      {\n        sorry: "You have been fired.",\n        hrEmail: "hr@bigco.com",\n      },\n      { status: 401 }\n    );\n  }\n}\n\nfunction ErrorBoundary() {\n  const error = useRouteError();\n\n  if (isRouteErrorResponse(error) && error.status === 401) {\n    // the response json is automatically parsed to\n    // `error.data`, you also have access to the status\n    return (\n      <div>\n        <h1>{error.status}</h1>\n        <h2>{error.data.sorry}</h2>\n        <p>\n          Go ahead and email {error.data.hrEmail} if you\n          feel like this is a mistake.\n        </p>\n      </div>\n    );\n  }\n\n  // rethrow to let the parent error boundary handle it\n  // when it\'s not a special case for this route\n  throw error;\n}\n'})}),"\n",(0,o.jsx)(r.p,{children:"This makes it possible to create a general error boundary, usually on your root route, that handles many cases:"}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:"function RootBoundary() {\n  const error = useRouteError();\n\n  if (isRouteErrorResponse(error)) {\n    if (error.status === 404) {\n      return <div>This page doesn't exist!</div>;\n    }\n\n    if (error.status === 401) {\n      return <div>You aren't authorized to see this</div>;\n    }\n\n    if (error.status === 503) {\n      return <div>Looks like our API is down</div>;\n    }\n\n    if (error.status === 418) {\n      return <div>\ud83e\uded6</div>;\n    }\n  }\n\n  return <div>Something went wrong</div>;\n}\n"})}),"\n",(0,o.jsx)(r.h2,{id:"abstractions",children:"Abstractions"}),"\n",(0,o.jsx)(r.p,{children:"This pattern of throwing when you know you can't continue down the data loading path you're on makes it pretty simple to properly handle exceptional situations."}),"\n",(0,o.jsx)(r.p,{children:"Imagine a function that gets the user's web token for authorized requests looking something like this:"}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:'async function getUserToken() {\n  const token = await getTokenFromWebWorker();\n  if (!token) {\n    throw new Response("", { status: 401 });\n  }\n  return token;\n}\n'})}),"\n",(0,o.jsx)(r.p,{children:"No matter which loader or action uses that function, it will stop executing code in the current call stack and send the app over to the error path instead."}),"\n",(0,o.jsx)(r.p,{children:"Now let's add a function that fetches a project:"}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:'function fetchProject(id) {\n  const token = await getUserToken();\n  const response = await fetch(`/projects/${id}`, {\n    headers: { Authorization: `Bearer ${token}` },\n  });\n\n  if (response.status === 404) {\n    throw new Response("Not Found", { status: 404 });\n  }\n\n  // the fetch failed\n  if (!response.ok) {\n    throw new Error("Could not fetch project");\n  }\n}\n'})}),"\n",(0,o.jsxs)(r.p,{children:["Thanks to ",(0,o.jsx)(r.code,{children:"getUserToken"}),", this code can assume it gets a token. If there isn't one, the error path will be rendered. Then if the project doesn't exist, no matter which loader is calling this function, it will throw a 404 over to the ",(0,o.jsx)(r.code,{children:"errorElement"}),". Finally, if the fetch fails completely, it will send an error."]}),"\n",(0,o.jsxs)(r.p,{children:['At any time you realize "I don\'t have what I need", you can simply ',(0,o.jsx)(r.code,{children:"throw"}),", knowing that you're still rendering something useful for the end user."]}),"\n",(0,o.jsx)(r.p,{children:"Let's put it together into a route:"}),"\n",(0,o.jsx)(r.pre,{children:(0,o.jsx)(r.code,{className:"language-tsx",children:'<Route\n  path="/"\n  element={<Root />}\n  errorElement={<RootBoundary />}\n>\n  <Route\n    path="projects/:projectId"\n    loader={({ params }) => fetchProject(params.projectId)}\n    element={<Project />}\n  />\n</Route>\n'})}),"\n",(0,o.jsxs)(r.p,{children:["The project route doesn't have to think about errors at all. Between the loader utility functions like ",(0,o.jsx)(r.code,{children:"fetchProject"})," and ",(0,o.jsx)(r.code,{children:"getUserToken"})," throwing whenever something isn't right, and the ",(0,o.jsx)(r.code,{children:"RootBoundary"})," handling all of the cases, the project route gets to focus strictly on the happy path."]})]})}function h(e={}){const{wrapper:r}={...(0,t.a)(),...e.components};return r?(0,o.jsx)(r,{...e,children:(0,o.jsx)(c,{...e})}):c(e)}},1151:(e,r,n)=>{n.d(r,{Z:()=>i,a:()=>a});var o=n(7294);const t={},s=o.createContext(t);function a(e){const r=o.useContext(s);return o.useMemo((function(){return"function"==typeof e?e(r):{...r,...e}}),[r,e])}function i(e){let r;return r=e.disableParentContext?"function"==typeof e.components?e.components(t):e.components||t:a(e.components),o.createElement(s.Provider,{value:r},e.children)}}}]);